# Polis Release Configuration
# This file contains configuration for building and releasing Polis

[package]
name = "polis"
version = "0.1.0"
description = "Polis - Container Runtime and Orchestration Platform"
authors = ["Polis Team"]
license = "MIT"
repository = "https://github.com/polis-project/polis"
homepage = "https://polis.dev"
keywords = ["container", "runtime", "orchestration", "docker", "kubernetes"]
categories = ["command-line-utilities", "development-tools"]

[build]
# Build configuration
target_dir = "target"
release_dir = "release"
clean_before_build = true
parallel_builds = true

# Platform targets
[build.targets]
linux = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]
macos = [
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]
windows = [
    "x86_64-pc-windows-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc"
]

# Release configuration
[release]
# Version information
version = "0.1.0"
prerelease = false
draft = false

# Release notes
[release.notes]
template = """
# Polis v{version}

## What's New
- Initial release of Polis Container Runtime
- Complete container lifecycle management
- Advanced orchestration features
- Service discovery and load balancing
- Auto-scaling capabilities
- Health monitoring
- REST and gRPC APIs
- Comprehensive security features

## Installation
See the [Installation Guide](docs/INSTALLATION.md) for detailed instructions.

## Quick Start
```bash
# Start Polis server
polis-cli server start

# Create a container
polis-cli container create --name my-container --image alpine:latest

# List containers
polis-cli container list
```

## Documentation
- [User Guide](docs/USER_GUIDE.md)
- [API Reference](docs/API_REFERENCE.md)
- [Developer Guide](docs/DEVELOPER_GUIDE.md)

## Support
- [GitHub Issues](https://github.com/polis-project/polis/issues)
- [Discord Community](https://discord.gg/polis)
- [Documentation](https://docs.polis.dev)
"""

# Package configuration
[packages]
# Binary packages
[packages.binaries]
polis-cli = { 
    name = "polis-cli", 
    description = "Polis Command Line Interface",
    features = ["cli"]
}

# Library packages
[packages.libraries]
polis-core = { 
    name = "polis-core", 
    description = "Polis Core Library",
    features = ["default"]
}
polis-runtime = { 
    name = "polis-runtime", 
    description = "Polis Container Runtime",
    features = ["default"]
}
polis-api = { 
    name = "polis-api", 
    description = "Polis API Library",
    features = ["default"]
}
polis-orchestrator = { 
    name = "polis-orchestrator", 
    description = "Polis Orchestration Library",
    features = ["default"]
}

# Docker configuration
[docker]
# Base images
[docker.images]
linux = "debian:bookworm-slim"
windows = "mcr.microsoft.com/windows/servercore:ltsc2022"

# Docker build configuration
[docker.build]
context = "."
dockerfile = "Dockerfile"
platforms = ["linux/amd64", "linux/arm64", "windows/amd64"]

# Docker tags
[docker.tags]
latest = "polis:latest"
versioned = "polis:{version}"
prerelease = "polis:{version}-{prerelease}"

# Distribution configuration
[distribution]
# Package formats
[distribution.formats]
linux = ["tar.gz", "deb", "rpm"]
macos = ["tar.gz", "dmg"]
windows = ["zip", "msi"]

# Package managers
[distribution.package_managers]
linux = ["apt", "yum", "dnf", "pacman", "snap", "flatpak"]
macos = ["homebrew", "macports"]
windows = ["chocolatey", "scoop", "winget"]

# Installation methods
[distribution.installation]
# Direct download
[distribution.installation.direct]
url = "https://github.com/polis-project/polis/releases/download/v{version}"
checksums = true

# Package managers
[distribution.installation.package_managers]
homebrew = "brew install polis-project/polis/polis"
chocolatey = "choco install polis"
snap = "snap install polis"

# CI/CD configuration
[ci]
# GitHub Actions
[ci.github_actions]
workflows = [
    "build.yml",
    "test.yml", 
    "release.yml",
    "security.yml"
]

# Build matrix
[ci.build_matrix]
rust = ["stable", "beta", "nightly"]
os = ["ubuntu-latest", "macos-latest", "windows-latest"]
arch = ["x64", "arm64"]

# Test configuration
[ci.test]
unit_tests = true
integration_tests = true
benchmarks = true
coverage = true
security_audit = true

# Security configuration
[security]
# Security features
[security.features]
seccomp = true
apparmor = true
selinux = true
capabilities = true
namespaces = true
cgroups = true

# Security scanning
[security.scanning]
cargo_audit = true
cargo_deny = true
clippy = true
rustfmt = true

# Vulnerability reporting
[security.vulnerabilities]
email = "security@polis.dev"
url = "https://github.com/polis-project/polis/security/advisories"

# Documentation configuration
[docs]
# Documentation sites
[docs.sites]
main = "https://docs.polis.dev"
api = "https://api-docs.polis.dev"
guides = "https://guides.polis.dev"

# Documentation formats
[docs.formats]
markdown = true
html = true
pdf = true
epub = true

# Documentation generation
[docs.generation]
mdbook = true
rustdoc = true
cargo_doc = true

# Community configuration
[community]
# Communication channels
[community.channels]
discord = "https://discord.gg/polis"
github = "https://github.com/polis-project/polis"
twitter = "https://twitter.com/polis_project"
reddit = "https://reddit.com/r/polis"

# Contribution
[community.contribution]
code_of_conduct = "CODE_OF_CONDUCT.md"
contributing = "CONTRIBUTING.md"
issue_templates = true
pr_templates = true

# Governance
[community.governance]
maintainers = ["polis-team"]
reviewers = ["polis-reviewers"]
approvers = ["polis-approvers"]

# Metrics and monitoring
[metrics]
# Performance metrics
[metrics.performance]
build_time = true
test_time = true
binary_size = true
memory_usage = true

# Quality metrics
[metrics.quality]
test_coverage = true
code_complexity = true
maintainability = true
security_score = true

# Release metrics
[metrics.release]
download_count = true
install_count = true
usage_stats = true
error_reports = true

# Legal configuration
[legal]
# Licenses
[legal.licenses]
code = "MIT"
documentation = "CC-BY-4.0"
assets = "CC-BY-4.0"

# Copyright
[legal.copyright]
year = 2024
holder = "Polis Project Contributors"

# Trademark
[legal.trademark]
name = "Polis"
registration = "pending"

# Privacy
[legal.privacy]
policy = "PRIVACY.md"
gdpr_compliant = true
ccpa_compliant = true
